"""
Synthesizer node — the final node in the graph.

This node takes all the data collected by previous nodes (city summary,
weather forecast, images) and packages it into a structured TravelResponse
object. For follow-up queries, it uses the LLM to generate a weather-aware
conversational response that reasons about the data.

The Streamlit frontend parses this structured output to render the UI
components — it never sees raw markdown or unstructured text.
"""

from langchain_core.messages import HumanMessage, SystemMessage

from agents.state import AgentState
from models.schemas import TravelResponse, WeatherDataPoint, CityImage
from utils.helpers import get_llm


def _generate_weather_insight(city: str, user_input: str, weather_data: list) -> str:
    """Use the LLM to reason about weather data for follow-up queries.

    This is what makes the assistant intelligent — instead of just showing
    a chart, it actually interprets the data and gives actionable advice.
    E.g., 'Is it good for boating next week?' → checks rain probability.
    """
    if not weather_data or not user_input:
        return ""

    # Format weather data for the LLM
    weather_text = "\n".join(
        f"- {w.get('date', 'N/A')}: {w.get('condition', 'N/A')}, "
        f"High {w.get('temperature_high', 'N/A')}°C / Low {w.get('temperature_low', 'N/A')}°C, "
        f"Rain probability: {w.get('precipitation_chance', 0)}%, "
        f"Humidity: {w.get('humidity', 'N/A')}%"
        for w in weather_data
        if isinstance(w, dict)
    )

    if not weather_text:
        return ""

    prompt = (
        f"User asked: \"{user_input}\"\n"
        f"City: {city}\n\n"
        f"Weather forecast data:\n{weather_text}\n\n"
        f"Based on this weather data, give a helpful, conversational response. "
        f"Analyze the rain probabilities, temperatures, and conditions to give "
        f"practical advice. If they're asking about outdoor activities, check "
        f"the rain chance. Be specific about which days look best."
    )

    try:
        llm = get_llm()
        response = llm.invoke([
            SystemMessage(content=(
                "You are VEXHALIA, an AI travel assistant. Analyze weather data "
                "and give practical, conversational advice. Be specific about dates "
                "and conditions. Keep it to 100-150 words."
            )),
            HumanMessage(content=prompt),
        ])
        return response.content
    except Exception:
        return ""


def synthesizer_node(state: AgentState) -> dict:
    """Compose the final structured output from all collected data.

    For follow-up queries, enriches the summary with weather-aware
    insights generated by the LLM.
    """
    city = state.get("city_name", "Unknown")
    summary = state.get("city_summary", "")
    weather_data = state.get("weather_forecast", [])
    image_urls = state.get("image_urls", [])
    images_raw = state.get("images", [])
    source = state.get("data_source", "unknown")
    user_input = state.get("user_input", "")
    is_follow_up = state.get("is_follow_up", False)

    # Build the weather forecast list — handle both dict and model forms
    forecast = []
    for item in weather_data:
        if isinstance(item, dict):
            forecast.append(WeatherDataPoint(**item))
        elif isinstance(item, WeatherDataPoint):
            forecast.append(item)

    # Build the images list
    images = []
    for item in images_raw:
        if isinstance(item, dict):
            images.append(CityImage(**item))
        elif isinstance(item, CityImage):
            images.append(item)

    # For follow-up queries, generate weather-aware insights
    if is_follow_up and weather_data:
        weather_insight = _generate_weather_insight(
            city, user_input, weather_data
        )
        if weather_insight:
            summary = weather_insight

    # If we have no summary, provide a fallback message
    if not summary:
        summary = (
            f"We gathered information about {city} but could not generate "
            f"a detailed summary. Please check your LLM API key configuration."
        )

    # If we have images but not URLs (or vice versa), sync them
    if images and not image_urls:
        image_urls = [img.url for img in images]
    elif image_urls and not images:
        images = [CityImage(url=url, caption=f"View of {city}") for url in image_urls]

    # Build the final response object
    response = TravelResponse(
        city_name=city,
        city_summary=summary,
        weather_forecast=forecast,
        image_urls=image_urls,
        images=images,
        data_source=source,
    )

    # Store the serialized response in state for the UI to consume
    return {
        "city_summary": response.city_summary,
        "weather_forecast": [wp.model_dump() for wp in response.weather_forecast],
        "image_urls": response.image_urls,
        "images": [img.model_dump() for img in response.images],
        "data_source": response.data_source,
    }
